### ISSUE TITLE
Broken device table

### ISSUE THREAD

**Issue by hudsonbrendon** [dmamontov/hass-miwifi#22] opened 2022-03-28 00:13 UTC
Hello, I added the example of the device table present in the documentation, and it was rendered for me like this:

![image](https://user-images.githubusercontent.com/5201888/160307232-f590f851-019e-4724-80f5-ac50d7489c55.png)

I installed all the cards and still the error, any solution?

this is my card currently:

I edited the names, and added the MAC of the device.

https://gist.github.com/hudsonbrendon/75d6f2f53bf03906f205adae85bf56bb

**Comment by dmamontov** [comment] 2022-03-28 10:42
What version of flex-table-card do you have?

**Comment by vinulac** [comment] 2022-03-29 19:53
Hi, 
I had the same problem and fixed it by changing this setting.

![Capture d’écran 2022-03-29 214900](https://user-images.githubusercontent.com/76621527/160695765-1ef17212-6185-4a75-8490-8990873651ca.png)

**Comment by dmamontov** [comment] 2022-04-03 17:11
Duplicate of #21

**Closed by dmamontov** 2022-04-03 17:11 UTC
